FROM bitnami/spark:3.4.1
USER root
RUN apt-get update && apt-get install -y openjdk-11-jdk curl
COPY spark-job /opt/spark-job
WORKDIR /opt/spark-job
RUN curl -s https://get.sdkman.io | bash && \
    bash -c "source $HOME/.sdkman/bin/sdkman-init.sh && sdk install sbt"
ENTRYPOINT ["sbt", "run"]